// Your Supabase project details — replace both values below.
// Find them at: supabase.com → your project → Settings → API

const SUPABASE_URL = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuZmhmd3Bnb2t6cGZpZGFvb2RhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4OTQyMTQ4MSwiZXhwIjoyMTA0OTk3NDgxfQ.zR_Ebv1BrXJlkKSfFDwXewZpohKVcY1oS7Xk6qt4nGY'
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuZmhmd3Bnb2t6cGZpZGFvb2RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk0MjE0ODEsImV4cCI6MjEwNDk5NzQ4MX0.UfAqnmpCXAetrdcpFS14KjMzdSzkME2SJH77Ws-PoaA'
